write_hydrogenated: False
minimise_hydrogens: False
minimisation_steps: 50
minimisation_forcefield: "MMFF94"
minimisation_method: "ConjugateGradients"
vdw_comp: 0.1
interacting_cutoff: 5.0
ph: 7.4           
include_sequence_adjacent: False
use_ambiguities: False
output: "arpeggio_output"
chem_comp: |
  #
  loop_
  _chem_comp.formula
  _chem_comp.formula_weight
  _chem_comp.id
  _chem_comp.mon_nstd_flag
  _chem_comp.name
  _chem_comp.pdbx_synonyms
  _chem_comp.type
  "C3 H7 N O2"         89.093  ALA y ALANINE                              ? "L-PEPTIDE LINKING"
  "C6 H15 N4 O2"       175.209 ARG y ARGININE                             ? "L-PEPTIDE LINKING"
  "C4 H8 N2 O3"        132.118 ASN y ASPARAGINE                           ? "L-PEPTIDE LINKING"
  "C4 H7 N O4"         133.103 ASP y "ASPARTIC ACID"                      ? "L-PEPTIDE LINKING"
  "C3 H7 N O2 S"       121.158 CYS y CYSTEINE                             ? "L-PEPTIDE LINKING"
  "C5 H10 N2 O3"       146.144 GLN y GLUTAMINE                            ? "L-PEPTIDE LINKING"
  "C5 H9 N O4"         147.129 GLU y "GLUTAMIC ACID"                      ? "L-PEPTIDE LINKING"
  "C2 H5 N O2"         75.067  GLY y GLYCINE                              ? "PEPTIDE LINKING"
  "C6 H10 N3 O2"       156.162 HIS y HISTIDINE                            ? "L-PEPTIDE LINKING"
  "C6 H13 N O2"        131.173 ILE y ISOLEUCINE                           ? "L-PEPTIDE LINKING"
  "C6 H13 N O2"        131.173 LEU y LEUCINE                              ? "L-PEPTIDE LINKING"
  "C6 H15 N2 O2"       147.195 LYS y LYSINE                               ? "L-PEPTIDE LINKING"
  "C5 H11 N O2 S"      149.211 MET y METHIONINE                           ? "L-PEPTIDE LINKING"
  "C9 H11 N O2"        165.189 PHE y PHENYLALANINE                        ? "L-PEPTIDE LINKING"
  "C5 H9 N O2"         115.130 PRO y PROLINE                              ? "L-PEPTIDE LINKING"
  "C3 H7 N O3"         105.093 SER y SERINE                               ? "L-PEPTIDE LINKING"
  "C4 H9 N O3"         119.119 THR y THREONINE                            ? "L-PEPTIDE LINKING"
  "C11 H12 N2 O2"      204.225 TRP y TRYPTOPHAN                           ? "L-PEPTIDE LINKING"
  "C9 H11 N O3"        181.189 TYR y TYROSINE                             ? "L-PEPTIDE LINKING"
  "C5 H11 N O2"        117.146 VAL y VALINE                               ? "L-PEPTIDE LINKING"
  "Zn 2"               65.409  ZN  . "ZINC ION"                           ? "non-polymer"
  "MG 2"               24.305  MG  . "MAGNESIUM ION"                      ? "non-polymer"
  "Ca 2"               40.078  CA  . "CALCIUM ION"                        ? "non-polymer"
  "H2 O"               18.015  HOH . "WATER"                              ? "non-polymer" 
  "C10 H16 N5 O13 P3"  507.181 ATP . "ADENOSINE-5'-TRIPHOSPHATE"          ? "non-polymer"        
  "C10 H15 N5 O10 P2"  427.201 ADP n "ADENOSINE-5'-DIPHOSPHATE"           ? "non-polymer"
  "C10 H14 N5 O6 P"    331.222 DA  y "2'-DEOXYADENOSINE-5'-MONOPHOSPHATE" ? "DNA linking"
  "C9 H14 N3 O7 P"     307.197 DC  y "2'-DEOXYCYTIDINE-5'-MONOPHOSPHATE"  ? "DNA linking"
  "C10 H14 N5 O7 P"    347.221 DG  y "2'-DEOXYGUANOSINE-5'-MONOPHOSPHATE" ? "DNA linking"
  "C10 H15 N2 O8 P"    322.208 DT  y "THYMIDINE-5'-MONOPHOSPHATE"         ? "DNA linking"  
  #
